kind = "DojoContract"
class_hash = "0x578e0e3a292bf55a5d322f44ae97e4aa0da33d4751d79bc512d5f337cdfa7ae"
original_class_hash = "0x578e0e3a292bf55a5d322f44ae97e4aa0da33d4751d79bc512d5f337cdfa7ae"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/overdrive-gameActions-13efaa45.json"
reads = []
writes = []
init_calldata = []
tag = "overdrive-gameActions"
systems = [
    "create_game",
    "get_game",
    "set_player",
]
manifest_name = "overdrive-gameActions-13efaa45"
