kind = "DojoContract"
class_hash = "0x4dd082c2d32b55d2becb43655e15f85142b24cc9fbc7d276a1e0bdf90d9f426"
original_class_hash = "0x4dd082c2d32b55d2becb43655e15f85142b24cc9fbc7d276a1e0bdf90d9f426"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/overdrive-playerActions-3f98d0d2.json"
reads = []
writes = []
init_calldata = []
tag = "overdrive-playerActions"
systems = [
    "create_account",
    "get_account",
]
manifest_name = "overdrive-playerActions-3f98d0d2"
