[world]
name = "Overdrive"
description = "Fully onchain racing/strategy game."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/fernelabs/overdrive-onchain"
seed = "overdrive"

[world.socials]
x = "https://x.com/fernelabs"
github = "https://github.com/fernelabs/overdrive-onchain"

[namespace]
default = "overdrive"

[writers]
"overdrive-PlayerAccount" = ["overdrive-playerActions", "overdrive-gameActions"]
"overdrive-PlayerAssets" = ["overdrive-playerActions", "overdrive-gameActions"]
"overdrive-PlayerState" = ["overdrive-playerActions", "overdrive-gameActions"]
"overdrive-PlayerCiphers" = ["overdrive-playerActions", "overdrive-gameActions"]
"overdrive-GameState" = ["overdrive-playerActions", "overdrive-gameActions"]

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x041023eff4fa7119869a4280237d47d6b5693e49820039c147098e222978d067"
