#!/usr/bin/bash

if [[ $1 == "help" ]]; then
    echo -e "\nThis helps you to interact with sozo in an easier way.\n";
    echo -e "\nUsage:";
    echo -e "   ./run [help] [build] [create USERNAME] [init] [get] [request GAME_ID] [set GAME_ID CIPHER_VALUE CIPHER_TYPE]"
    echo -e "\nOptions:";
    echo -e "   help                                  Show this message";
    echo -e "   build                                 Run build and migrate";
    echo -e "   create USERNAME                       Create user";
    echo -e "   get                                   Get user";
    echo -e "   init                                  Initialize game";
    echo -e "   state                                 Get game state";
    echo -e "   request GAME_ID                       Request ciphers";
    echo -e "   set GAME_ID CIPHER_VALUE CIPHER_TYPE  Set player state";
    exit 1;
fi

if [[ $1 == "build" ]]; then
   sozo build;
   sozo migrate apply;
fi

if [[ $1 == "create" ]]; then
   sozo execute overdrive-playerActions create_account -c sstr:$2
fi

if [[ $1 == "get" ]]; then
   sozo execute overdrive-playerActions get_account
fi

if [[ $1 == "init" ]]; then
   sozo execute overdrive-gameActions create_game
fi

if [[ $1 == "state" ]]; then
   sozo execute overdrive-gameActions get_game
fi

if [[ $1 == "request" ]]; then
   sozo execute overdrive-gameActions get_cipher -c $(($2))
fi

if [[ $1 == "set" ]]; then
   sozo execute overdrive-gameActions set_player -c $(($2)),u256:$(($3)),$(($4))
fi
