#!/usr/bin/bash

if [[ $1 == "help" ]]; then
    echo -e "\nThis helps you to interact with sozo in an easier way.\n";
    echo -e "\nUsage:";
    echo -e "   ./run [help] [build] [create USERNAME] [init GAME_MODE] [request IS_BOT] [run PARAMS]"
    echo -e "\nOptions:";
    echo -e "   help                                  Show this message";
    echo -e "   build                                 Run build and migrate";
    echo -e "   katana                                Run Katana instance";
    echo -e "   torii                                 Run Torii instance";
    echo -e "   create USERNAME                       Create user";
    echo -e "   init GAME_MODE                        Initialize game";
    echo -e "   request IS_BOT                        Request ciphers";
    echo -e "   module PARAMS                         Run cipher module. Params are int:ARRAY_SIZE,[TYPE,VALUE],IS_BOT";
    exit 1;
fi

if [[ $1 == "build" ]]; then
   sozo build;
   sozo migrate apply;
fi

if [[ $1 == "katana" ]]; then
   katana --disable-fee
fi

if [[ $1 == "torii" ]]; then
   torii --world 0x611ff61e3381fcab007822cddc4ab3c68983b1450cc61e37eefbbf7699e116d
fi

if [[ $1 == "create" ]]; then
   sozo execute overdrive-playerActions create_player -c sstr:$2
fi

if [[ $1 == "init" ]]; then
   sozo execute overdrive-gameActions create_game -c $(($2))
fi

if [[ $1 == "request" ]]; then
   sozo execute overdrive-playerActions hack_ciphers -c $(($2))
fi

if [[ $1 == "module" ]]; then
   sozo execute overdrive-playerActions run_cipher_module -c $2
fi