[package]
cairo-version = "=2.8.4"
name = "overdrive"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[scripts]
migrate = "sozo build && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.1" }

[features]
default = []