[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x611ff61e3381fcab007822cddc4ab3c68983b1450cc61e37eefbbf7699e116d"
transaction_hash = "0x6507cd4fe9c4a986c2c2def6ced57e9d550d8f2f11505e6c251fd0aadcd89e3"
block_number = 3
seed = "overdrive"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x4d31d4c01df195fdaafb0cc51d6edd74d38f3a0b01029727ade2e29a6b46454"
class_hash = "0x3227a421c1e9822b0966f7d5505f189bd12dc3133faab983a5d42ae35c3c8c0"
original_class_hash = "0x3227a421c1e9822b0966f7d5505f189bd12dc3133faab983a5d42ae35c3c8c0"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/overdrive-gameActions-13efaa45.json"
reads = []
writes = [
    "overdrive-Game",
    "overdrive-GamePlayer",
]
init_calldata = []
tag = "overdrive-gameActions"
systems = [
    "create_game",
    "get_game",
    "set_player",
]
manifest_name = "overdrive-gameActions-13efaa45"

[[contracts]]
kind = "DojoContract"
address = "0x27b2eafa764cb28435cc57798b3f1859258e28d3eb496e46098f5df2bedb2a8"
class_hash = "0x4dd082c2d32b55d2becb43655e15f85142b24cc9fbc7d276a1e0bdf90d9f426"
original_class_hash = "0x4dd082c2d32b55d2becb43655e15f85142b24cc9fbc7d276a1e0bdf90d9f426"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/overdrive-playerActions-3f98d0d2.json"
reads = []
writes = [
    "overdrive-Garage",
    "overdrive-Account",
]
init_calldata = []
tag = "overdrive-playerActions"
systems = [
    "create_account",
    "get_account",
]
manifest_name = "overdrive-playerActions-3f98d0d2"

[[models]]
kind = "DojoModel"
class_hash = "0x8690426590e0c9870e80e5ce2a4b7bf9fd3758ac589dd726122eb0a3c0472e"
original_class_hash = "0x8690426590e0c9870e80e5ce2a4b7bf9fd3758ac589dd726122eb0a3c0472e"
abi = "manifests/dev/deployment/abis/models/overdrive-Account-362da729.json"
tag = "overdrive-Account"
qualified_path = "overdrive::models::player_models::account"
manifest_name = "overdrive-Account-362da729"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "username"
type = "felt252"
key = false

[[models.members]]
name = "total_games_played"
type = "u256"
key = false

[[models.members]]
name = "total_games_won"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x604cf0100b50908a6d9fee20eaeeb0544c8be6fd1e84f29b037e1df13b791a6"
original_class_hash = "0x604cf0100b50908a6d9fee20eaeeb0544c8be6fd1e84f29b037e1df13b791a6"
abi = "manifests/dev/deployment/abis/models/overdrive-Game-2fa5a9e6.json"
tag = "overdrive-Game"
qualified_path = "overdrive::models::game_models::game"
manifest_name = "overdrive-Game-2fa5a9e6"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "created_by"
type = "ContractAddress"
key = false

[[models.members]]
name = "game_status"
type = "GameStatus"
key = false

[[models.members]]
name = "game_mode"
type = "GameMode"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7eabe6c5c2922d0b77989c8f5a28b29cc85497aa11f82589400da7bd07482a8"
original_class_hash = "0x7eabe6c5c2922d0b77989c8f5a28b29cc85497aa11f82589400da7bd07482a8"
abi = "manifests/dev/deployment/abis/models/overdrive-GamePlayer-4368b55a.json"
tag = "overdrive-GamePlayer"
qualified_path = "overdrive::models::game_models::game_player"
manifest_name = "overdrive-GamePlayer-4368b55a"

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "game_id"
type = "felt252"
key = true

[[models.members]]
name = "car"
type = "u256"
key = false

[[models.members]]
name = "score"
type = "u256"
key = false

[[models.members]]
name = "energy"
type = "u256"
key = false

[[models.members]]
name = "shield"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4cbab47929f8f3ccf9deca59a40b668dff129c6e21b78563d8ed663d52770a8"
original_class_hash = "0x4cbab47929f8f3ccf9deca59a40b668dff129c6e21b78563d8ed663d52770a8"
abi = "manifests/dev/deployment/abis/models/overdrive-Garage-376ec3a2.json"
tag = "overdrive-Garage"
qualified_path = "overdrive::models::player_models::garage"
manifest_name = "overdrive-Garage-376ec3a2"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "cars"
type = "u32"
key = false
