kind = "DojoModel"
class_hash = "0x8690426590e0c9870e80e5ce2a4b7bf9fd3758ac589dd726122eb0a3c0472e"
original_class_hash = "0x8690426590e0c9870e80e5ce2a4b7bf9fd3758ac589dd726122eb0a3c0472e"
abi = "manifests/dev/base/abis/models/overdrive-Account-362da729.json"
tag = "overdrive-Account"
qualified_path = "overdrive::models::player_models::account"
manifest_name = "overdrive-Account-362da729"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "username"
type = "felt252"
key = false

[[members]]
name = "total_games_played"
type = "u256"
key = false

[[members]]
name = "total_games_won"
type = "u256"
key = false
