kind = "DojoModel"
class_hash = "0x27858b7abc321a7945d1791a649ac6817a9307b3250420a107a36bb8b58ceac"
original_class_hash = "0x27858b7abc321a7945d1791a649ac6817a9307b3250420a107a36bb8b58ceac"
abi = "manifests/dev/base/abis/models/overdrive-Statistics-752811ea.json"
tag = "overdrive-Statistics"
qualified_path = "overdrive::models::player_models::statistics"
manifest_name = "overdrive-Statistics-752811ea"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "wins"
type = "u8"
key = false

[[members]]
name = "elo"
type = "u32"
key = false
