kind = "DojoModel"
class_hash = "0x7eabe6c5c2922d0b77989c8f5a28b29cc85497aa11f82589400da7bd07482a8"
original_class_hash = "0x7eabe6c5c2922d0b77989c8f5a28b29cc85497aa11f82589400da7bd07482a8"
abi = "manifests/dev/base/abis/models/overdrive-GamePlayer-4368b55a.json"
tag = "overdrive-GamePlayer"
qualified_path = "overdrive::models::game_models::game_player"
manifest_name = "overdrive-GamePlayer-4368b55a"

[[members]]
name = "owner"
type = "ContractAddress"
key = true

[[members]]
name = "game_id"
type = "felt252"
key = true

[[members]]
name = "car"
type = "u256"
key = false

[[members]]
name = "score"
type = "u256"
key = false

[[members]]
name = "energy"
type = "u256"
key = false

[[members]]
name = "shield"
type = "u256"
key = false
